{"name": "Wrong Credential Authentification Failed Test", "status": "passed", "start": 1713089486429, "stop": 1713089540307, "uuid": "10d15084-8ded-4b15-9ffd-4728539fe078", "historyId": "9517ee356c092075ea995a18ebb7544f", "testCaseId": "9517ee356c092075ea995a18ebb7544f", "fullName": "test.test_user_authorization_chrome.TestUserAuth#test_invalid_creds", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_authorization_chrome"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "DESKTOP-84P9B6H"}, {"name": "thread", "value": "1368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_authorization_chrome"}]}