{"name": "Wrong Credential Authentification Failed Test", "status": "passed", "start": 1713356115456, "stop": 1713356162870, "uuid": "32ba65de-6138-497f-987a-577418e71759", "historyId": "9517ee356c092075ea995a18ebb7544f", "testCaseId": "9517ee356c092075ea995a18ebb7544f", "fullName": "test.test_user_authorization_chrome.TestUserAuth#test_invalid_creds", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_authorization_chrome"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "DESKTOP-84P9B6H"}, {"name": "thread", "value": "10628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_authorization_chrome"}]}